In [1]:
print('Hello World')

Hello World


In [2]:
print?

In [9]:
s='hello there'
print(s)

hello there


In [10]:
%run my_File.ipynb

Hello World
hello there


In [19]:
%who
type(s)

s	 


str

In [1]:
%quickref

In [6]:
import numpy as np

data=np.loadtxt(fname='PyPractice/data/inflammation-01.csv',delimiter=',')
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [9]:
#let's get some info about the data array

print(type(data)) #tells us this is an n dimensional array

print(data.dtype) #tells us what is actually in the array

print(data.shape) #60 rows, 40 columns

<class 'numpy.ndarray'>
float64
(60, 40)


In [11]:
#calling specific values requires indexing with brackets
print('first value in data: ', data[0,0])
print('third value in data: ', data[0,2])#row zero column 2


first value in data:  0.0
third value in data:  1.0


In [15]:
# a simple for loop to sum numbers
numbers=[1,3,45,6,87,29]
total = 0
for interval in numbers:
    total = total + interval
print('total: ',total)


#or simply use the built in function
print(sum(numbers))

# note that this loop does not need to use the iteration variable at all
count = 0
for intervar in numbers:
    count=count+1
print("count = ",count)

#or simply use length function
print(len(numbers))

total:  171
171
count =  6
6


In [39]:
#exercise 5.9.1
count=0
total=0
lastNumber=0
largest=0
print('working')



working


In [77]:
#exercise 5.9.1
count=0
total=0
lastNumber=0
largest=0
print('working')


while True:
    thisNumber=input('Enter a number: \n')
    #first make sure its a number
    try:
        thisNumber=int(thisNumber)              
        count=count+1
        total=total+thisNumber
        print('your number is ', thisNumber)
        if thisNumber>lastNumber and thisNumber > largest:
            largest=thisNumber
            lastNumber=thisNumber
        else:
            lastNumber=thisNumber       
    except:
        if thisNumber=="done":
            break
        else:
            print('please use only numbers')


    
print('Done!') 
print('count = ',count, '\ntotal= ',total, '\nAverage= ',total/count,'\nMax= ', largest)

working
Enter a number: 
4541657615649761
your number is  4541657615649761
Enter a number: 
poop
please use only numbers
Enter a number: 
66425
your number is  66425
Enter a number: 
done
Done!
count =  2 
total=  4541657615716186 
Average=  2270828807858093.0 
Max=  4541657615649761


In [50]:
#exercise 6.5.3
def countLetter(word,letter):
    count=0
    for character in word:
        if character == letter:
            count = count +1
    print(count)
#remember that count was defined before. If i want to save this new count variable, i need to say "return(count)"
    
countLetter('stringadingadiddydoo','d')

#you can test if the letter is in the word using in
"a" in 'banana'

5


True

In [66]:
#testing for methods

stuff="april and friends"
print(type(stuff))
dir((stuff))

#use dot notation for methods

newStuff=stuff.upper()
print(newStuff)

#let's try the find method
index=stuff.find('e')
print(index)

<class 'str'>
APRIL AND FRIENDS
13


In [73]:
help(str.count)

Help on method_descriptor:

count(...)
    S.count(sub[, start[, end]]) -> int
    
    Return the number of non-overlapping occurrences of substring sub in
    string S[start:end].  Optional arguments start and end are
    interpreted as in slice notation.



In [74]:
word='bananas'
word.count('a')


3

In [132]:

#chapter 7.2 
#download file from https://www.py4e.com/code3/mbox.txt
fhand = open('PyPractice/mbox.txt') #don't forget the quotation marks
print(fhand) #file handle 

count =0
for line in fhand: #line is a reserved word in python? 
    count=count+1
print('Line Count = ',count)


fhand_short=open('PyPractice/mbox-short.txt','r')
#if the file is too big for the main memory,
#make sure to write a loop to read the file in chunks

inp=fhand_short.read() #always save this as a variable because the .read() method can only be used the first time
print(len(inp))
#print(inp[0:20])

count=0
for line in inp:
    if line.startswith('From'):
        print(line)
        count+=1
print('line count= ',count)



<_io.TextIOWrapper name='PyPractice/mbox.txt' mode='r' encoding='cp1252'>
Line Count =  132045
94626
line count=  0


In [139]:
fhand_short=open('PyPractice/mbox-short.txt')
#inp=fhand_short.readlines() #always save this as a variable because the .read() method can only be used the first time
#print(len(inp)) #had to use readlines() to count each line rather than each character, or just use open

count=0
for line in fhand_short:
    line=line.rstrip() #removes extra spaces
    if line.startswith('F'):
        #print(line)
        count+=1
print('\n' in fhand_short)

print('line count= ',count)

False
line count=  55


In [140]:
fhand_short=open('PyPractice/mbox-short.txt')
